### PR TITLE
Added Copy Journal Favorites feature to the mounts priority list

### PR DESCRIPTION
**Pull request by Thex-PiedDroit**
Note: Missing localization

### CODE REVIEW

**Comment by mbattersby** [comment]
Hi! This is very cool and I love people writing code for me.

I apologise that real life is in the way at the moment and I won't have time to look at it for a while. I'm glad you solved your own problem, wonderful!

**Comment by Thex-PiedDroit** [comment]
Hi! No problem, take all the time you need, and please don't hesitate to be as nitpicky as you feel the need to if/when you eventually review it :)
Thank you for the cool addon!

**Comment by mbattersby** [comment]
Do you know much about github? Is there a way to merge your pull request into a new branch rather than into the main branch?

**Comment by Thex-PiedDroit** [comment]
I am not extremely well versed, but i see here that i can edit which branch i make the merge request for; so if you create a branch for it, i can change it to go onto that one

**Comment by mbattersby** [comment]
Thanks, I made a branch called copy_journal_favorites if you want to give it a try. I'd just prefer a way to try out your changes when I can without importing them straight into the release branch.

**Comment by Thex-PiedDroit** [comment]
Of course! Done :)

**Comment by mbattersby** [comment]
That seemed to work! Thanks!

**Pull request merged**
