### PR TITLE
Feature: Added expansion filtering

### PR DESCRIPTION
**Pull request by MrKumaPants**
Added expansion filtering for mounts. The expansion details file was taken from Mount Journal Enhanced.

### CODE REVIEW

**Comment by mbattersby** [comment]
Hi, this looks like some good work, I just won't have time to look at it until at least after the TWW pre-patch,.

Just from a quick glimpse it's definitely too English-focused right now. It should use the `expansionID` numbers the same way that `C_Item.GetItemInfo` returns `expansionID`, and then `GetExpansionName(expansionID)` to turn it into text as that will work in all languages automatically.

There is already a Blizzard-provided localization for "Expansion" in the global `EXPANSION_FILTER_TEXT` so need to localize ourselves.

Overall, I think I am leaning into this and family being better moved out into some kind of `LibMountInfo` where `LibMountInfo.GetMountInfoByID` could return a table with the things that aren't covered by C_MountJournal, or maybe all the C_MountJournal.GetMountInfoByID and GetMountInfoExtraByID fields merged into a name-indexed table with the extra fields. That last part might be too much to maintain.

Overall I wish I had never added the family filters because I spend _way_ too much time maintaining them instead of doing things I like and am good at, such as programming.

**Comment by mbattersby** [comment]
Mostly I want someone else who is super keen on it and up-to-the-minute to maintain LibMountInfo-1.0 for me :)

**Comment by MrKumaPants** [comment]
I was actually trying to find an API function to get the expansion name, but couldn't find it lol. Glad there's one I can update.

Maybe can convince author of Mount Journal Advanced to make a library. 😁

**Comment by mbattersby** [comment]
I've made a branch feature_mountinfo which is more or less how I think it should work.

I'm going to close this off since I won't merge this, but please submit another one against the feature_mountinfo branch when you get around to it. Like I said before, I definitely won't be merging any change like this until after TWW is sorted out.

**Pull request closed without merging**
